# Generated by Django 2.2 on 2019-05-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='author',
        ),
        migrations.RemoveField(
            model_name='place',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='place',
            name='published_date',
        ),
        migrations.AddField(
            model_name='place',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
