# Generated by Django 2.2 on 2019-05-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190501_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='num',
        ),
    ]
