# Generated by Django 2.2 on 2019-05-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_place_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
