# Generated by Django 2.2 on 2019-05-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_place_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('origin_place', models.TextField()),
                ('new_place', models.TextField()),
                ('rh_name', models.TextField()),
                ('specification', models.TextField()),
                ('rh_address', models.TextField()),
                ('rh_country', models.CharField(max_length=100)),
                ('actual', models.CharField(max_length=100)),
                ('url', models.TextField()),
            ],
        ),
    ]
