# Generated by Django 2.2 on 2019-05-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='imgs/', width_field=100),
        ),
    ]
